date: "20180406"
start_time: "11:21"
end_time: "12:08"
search_terms: 
  - "elevate"
  - "drakon"
  - "nrinfo"
  - "nrtcp" 
  - "154.145.113.18"
  - "61.167.39.128"
  - "./deploy/archive/libdrakon.freebsd.x64.so_152.111.159.139"
  - "/var/log/devc"
  - "foo"
  - "/var/log/devc"
  - "xxx"
  - "81.49.200.166" 
  - "78.205.235.65"
  - "200.36.109.21"
  - "139.123.0.113"
  - "152.111.159.139"
  - "200.36.109.214"
  - "shellcode_server"
  - "loaderDrakon.freebsd.x64"
  - "drakon.freebsd.x64"
  - "netrecon"
  - "(nrtcp fail)"
  - "(nrtcp success)"
  - "/tmp/vUgefal"
  - "/var/log/devc"
  - "/dev/gtx_dsa_675"
  - "91.49.200.18"
  - "nginx"
  - "/etc/passwd"
  - "/etc/group"
  - "stage 1"
  - "oc2"
  - "200.16.109.214"
  - "cmd_exec"
  - "vUgefal"
  - "139.123.0.133"
  - "sshd"




# "Date:"
#     "20180406"
# "Timespan:"
#     "11:21-12:08"
# "Event Log:"
#     "11:21" "HTTP post sent, exploit worked but no drakon connection to operator console"
#     "11.22" "Successful, connect back"
#     "11:33" "elevate"
#     "11:38" "nrinfo"
#     "11:39" "nrtcp 154.145.113.18 80"
#     "11:42" "nrtcp 61.167.39.128 80"
#     "12:04" "putfile ./deploy/archive/libdrakon.freebsd.x64.so_152.111.159.139 /var/log/devc"
#     "12:04" "ps"
#     "12:08" "inject foo 123"
#     "12:08" "inject /var/log/devc xxx"
#     "CADETS crashed, lost shell, no injection"
# "Adresses:" 
#     "{eth0:800}" "81.49.200.166" "(PORT 80)" "->" "128.55.12.167" "(PORT 8000)" "http_post"
#     "{eth0:801}" "78.205.235.65" "(PORT 80)" "->" "128.55.12.167" "(PORT 8001)" "shellcode_server"
#     "{eth0:802}" "200.36.109.214" "(PORT 80)" "->" "128.55.12.167" "(PORT 8002)" "loaderDrakon.freebsd.x64"
#     "{eth0:803}" "139.123.0.113" "(PORT 80)" "->" "128.55.12.167" "(PORT 8003)" "drakon.freebsd.x64"
#     "{eth0:804}" "152.111.159.139" "(PORT 80)" "->" "128.55.12.167" "(PORT 8004)" "libdrakon.freebsd.x64.so"
#     "{eth0:805}" "154.143.113.18" "(PORT 80)" "->" "128.55.12.167" "(PORT 8005)" "netrecon (nrtcp fail)"
#     "{eth0:806}" "61.167.39.128" "(PORT 80)" "->" "128.55.12.167" "(PORT 8006)" "netrecon (nrtcp success)"
# "Interactions:"
#     "Files:"
#         "F1>" "putfile" "./deploy/archive/drakon.freebsd.x64_139.123.0.113" "/tmp/vUgefal"
#         "F2>" "putfile" "./deploy/archive/libdrakon.freebsd.x64.so_152.111.159.139" "/var/log/devc"
#         "F2>" "inject" "/var/log/devc" "809"
#     "Processes:"
#         "F1>" "elevate" "/tmp/vUgefal"
#     "Connections:"
#         "exploit:" "connection on port" "(PORT 80)" "from" "81.49.200.166"
#         "nginx:" "connection to" "78.205.235.65" "(PORT 80)"
#         "nginx:" "connection to" "200.36.109.214" "(PORT 80)"
#         "vUgefal:" "connection to" "139.123.0.113" "(PORT 80)"
#         "F2>" "nrtcp" "154.145.113.18" "(PORT 80)" "(failed?)"
#         "F2>" "nrtcp" "61.167.39.128" "(PORT 80)"
# "Graph:"
#     "91.49.200.18" "connect (exploit 80)" "nginx"
#     "nginx" "read" "/etc/passwd"
#     "nginx" "read" "/etc/group"
#     "nginx" "connect (stage 1)" "78.205.235.65" "(PORT 80)"
#     "nginx" "connect (oc2)" "200.16.109.214" "(PORT 80)"
#     "nginx" "write (cmd_exec, cache)" "/dev/gtx_dsa_675"
#     "nginx" "putfile" "/tmp/vUgefal"
#     "nginx" "delete" "/tmp/vUgefal"
#     "/tmp/vUgefal" "new process (root)" "vUgefal (PID 7)"
#     "vUgefal" "(PID 7)" "read" "/etc/group"
#     "vUgefal" "(PID 7)" "read" "/etc/passwd"
#     "vUgefal" "(PID 7)" "connect (oc2)" "139.123.0.133" "(PORT 80)"
#     "vUgefal" "(PID 7)" "connect (netrecon tcp)" "154.145.113.18" "(PORT 8O)"
#     "vUgefal" "(PID 7)" "connect (netrecon scp)" "61.167.39.128" "(PORT 80)"
#     "vUgefal" "(PID 7)" "chmod" "/var/log/devc"
#     "vUgefal" "(PID 7)" "write" "/var/log/devc"
#     "vUgefal" "(PID 7)" "inject (devc)" "sshd (PID 8000)"