date: "20180411"
start_time: "15:08"
end_time: "15:15"
search_terms: 
  - "/tmp/grain"
  - "/etc/group"
  - "sshd"
  - "nignx" 
  - "25.159.96.207"
  - "76.56.184.25"
  - "155.162.39.48"
  - "198.115.236.119"
  - "128.55.12.167"
  - "loaderDrakon"
  - "shellcode_server"
  - "libdrakon"
  - "./deploy/archive/libdrakon.freebsd.x64.so_198.115.236.119"
  - "vUGefai"

# "Date:"
#     "20180411"
# "Timespan:"
#     "15:08-15:15"
# "Event Log:"
#     "15:08" "throw http payload"
# 	"15:10" "putfile ./deploy/archive/libdrakon.freebsd.x64.so_198.115.236.119 sendmail (failed)"
# 	"15:11" "rm vUGefai (failed)"
# 	"15:12" "putfile ./deploy/archive/libdrakon.freebsd.x64.so_198.115.236.119 grain"
# 	"15:15" "inject /tmp/grain 802"
# 	"15:15" "cadets crashed"
# "Adresses:" 
# 	"[eth0:920]" "25.159.96.207" "(PORT 80)" "->" "128.55.12.167" "(PORT 8040)" "http_post"
# 	"[eth0:921]" "76.56.184.25" "(PORT 80)" "->" "128.55.12.167" "(PORT 8041)" "shellcode_server"
# 	"[eth0:922]" "155.162.39.48" "(PORT 80" "->" "128.55.12.167" "(PORT 8042)" "loaderDrakon"
# 	"[eth0:923]" "198.115.236.119" "(PORT 80)" "->" "128.55.12.167" "(PORT 8043)" "libdrakon (failed)"
# "Interactions:"
#     "Files:"
#         "F1>" "putfile" " ./deploy/archive/libdrakon.freebsd.x64.so_198.115.236.119" "sendmail (failed)"
#         "F1>" "rm" "vUGefai" "(failed)"
#         "F1>" "putfile" "./deploy/archive/libdrakon.freebsd.x64.so_198.115.236.119" "grain"
#     "Processes:"
# 		"F1>" "inject" "/tmp/grain 802" "(failed and caused kernel panic)"
#     "Connections:"
#        	"exploit:" "connection on" "(PORT 80)" "from" "25.159.96.207"
#         "nginx:" "connection to" "76.56.184.25"
#         "nginx:" "connection to" "155.162.39.48" "(PORT 80)"
# "Graph:"
#     "25.159.96.207" "(PORT 80)" "connect (exploit 80)" "nginx"
#     "nginx" "read" "/etc/passwd"
#     "nginx" "read" "/etc/group"
#     "nginx" "connect (stage 1)" "76.56.184.25" "(PORT 80)"
#     "nginx" "connect (oc2)" "155.162.39.48" "(PORT 80)"
#     "nginx" "write" "/tmp/grain"
#     "nginx" "chmod" "/tmp/grain"
#     "nginx" "inject (grain)" "sshd (PID 802)"
#     "sshd (PID 802)" "crash" "kernel panic"
    